sudo: required

services:
  - docker

before_install:
  - docker pull alpine:latest

env:
  matrix:
    - CHANNEL=stable
    - CHANNEL=beta
    - CHANNEL=nightly

script:
  - chmod +x ./build.sh
  - ./build.sh ${CHANNEL}

before_deploy:
  - docker login \
      --username ${DOCKER_USERNAME} \
      --password ${DOCKER_PASSWORD}

deploy:

  - provider: script
    script: docker push aetheric/rust
    skip_cleanup: true
    on:
      branch: master
