sudo: required

services:
  - docker

env:

  global: 
    - secure: DcPcbZBB3TLwOI/6zkf6MH2T42Qos2uqN6ORZNtCX5Qp72eKJvJB3Hxxtlfg232Ym8sUI7YDVdwMChbLAZL596oF0YAgZ/KQ0VAnQNkNM4YUgzMZHKg/clXEpiSyOI1RI/Ap0HUF3iB1GIG2X3EBgU01JKCElRG2ib/JTjgc4DG6P+CNsSHlqGnTYQLR2e7Dabnk238dnX9zOc7U2FiZyD02TyoX9rcofdhopckw2adA7uj9Qp3n4fAgroJrrmX6YKuwDfl36ytSBPFDeqmSp1V0aEQ5ppPLlZPmAEuVr8lPZAhF8c7ZZ64t67ICUQapwVSPA+SkkuHEeQllIomXAjXESDv7OkZXlckWCIB+J4/vZgppTLcLyTaBPhc0R22rWbc7qC/kLDuiJ7yDGjJPzDsixHKOt5geytyD/qrQTXyqLycwLSBIgmlLsfq5rIG/nzdhWaS4u3Q5MNMiJg9CkpQCwyyDGG2awoho8gKlj9AmFGZU+vEp/fmR4B5U/FCQ4LVVR2Q7S3z8kXlVh93qiI1mT8EcCfUHm/i4VT3hBozsc2KoRDiPmPKppNpKyPM6qtAUWUA2j5IUyiBu9OuEMMwXA4uKWL9+3Vtm4DhabcpBTNMBg8h+e6lZ5rGmqKGyg5vCBlIbQ943gHTKhMPRNlQ59Ys5ZLR1X7xYxfTQn/w=
    - secure: AtLYpCJExePAg5EkMnC+DdiI1t8iidlZYdb7dM/1eKdmZTP+VPMzh8PWLc3Mvq/dvYQ0ItuuGtQjGxWzoqROZelKrGpP+XcJk9aWa7YYJBj+cnWad17GwlEBudgAceIJZwfRw+5BxBaX+BA4cCWEoVJzhPE6qVMt8zhXzD/W47aPwL2UJfhvaqedJN4YJgls5OVPjDhWzWbOk/9PWNsqvFtWJUE+9RIEh3epLC/dfljPHG/3egig6AubWSUGYC4vkn90MoFo5r6KX8vAgho60FqW/avNh2LkPpzwLwqY/JBTopuC4mBBrkwtqgMymhbLym2QxqTt1BFUSDRNuRy8HweLFY2f2dCV5d34iWqcJ450MVu57hueGTeZQVieh50z+bya1qiYpQXTNGEBQHfM7Htf8gpmvF7FXeO6qOtvuaT/y0dmfJjZzoncYQDKCtyt63ILlNSSbtS9F8z6RhCREiNOM7qD30BhrVeWRsKxkdRtBVUUOGY26oISTVZo30oe5+Iwk8RJ9e6yKsi/5x5MsubR1iAhyA0Ij2KhY2fHMLAA0wBA+XXyDT6r7IeL7THtFcRF2bqk7W6BPTjJQdeGPdVBxQAUtlcM1yy9qOYIZjGHuL6KAvWndHZm0Iy24Dg/MhMifgP+vBz3y55CFskhQVmNTZ5IWW2Tuscbn+o2W9M=

  matrix:
    - allow_failures:
      - CHANNEL=stable
    - CHANNEL=beta
    - CHANNEL=nightly

before_install:
  - docker pull alpine:latest
  - gem install gorgeous
  - chmod +x ./build.sh

install:
  - ./build.sh ${CHANNEL}

before_script:
  - docker login
      --username ${DOCKER_USERNAME}
      --password ${DOCKER_PASSWORD}
      docker.io

script:
  - docker push aetheric/rust:${CHANNEL}

