sudo: required

services:
  - docker

env:

  global:
    secure:

  matrix:
    - CHANNEL=stable
    - CHANNEL=beta
    - CHANNEL=nightly

before_install:
  - docker pull alpine:latest
  - gem install glorious
  - chmod +x ./build.sh

install:
  - ./build.sh ${CHANNEL}

before_script:
  - docker login \
      --username ${DOCKER_USERNAME} \
      --password ${DOCKER_PASSWORD}

script:
  - docker push aetheric/rust:${CHANNEL}

