sudo: required

services:
  - docker

before_install:
  - docker pull alpine:latest

env:
  matrix:
    - TOOLCHAIN=stable
    - TOOLCHAIN=beta
    - TOOLCHAIN=nightly

script:
  - docker build . \
      --env TOOLCHAIN=${TOOLCHAIN} \
      --tag aetheric/rust:${TOOLCHAIN}

before_deploy:
  - docker login \
      --username ${DOCKER_USERNAME} \
      --password ${DOCKER_PASSWORD}

deploy:
  
  - provider: script
    script: docker push aetheric/rust
    skip_cleanup: true
    on:
      branch: master

